name=M5UnitUnified
version=0.4.8
author=M5Stack
maintainer=M5Stack
sentence=M5UnitUnified is a library for unified handling of various M5 units products.
paragraph=
category=Device Control
url=https://github.com/m5stack/M5UnitUnified
architectures=esp32
includes=M5UnitUnified.h
depends=M5Utility (>=0.0.13),M5HAL (>=0.0.4)
