name=M5UnitUnified
version=0.5.5
author=M5Stack
maintainer=M5Stack
sentence=M5UnitUnified is a library for unified handling of various M5 units products.
paragraph=Unified hardware abstraction for M5Stack units with common APIs for I2C, GPIO, UART, and SPI communications.
category=Device Control
url=https://github.com/m5stack/M5UnitUnified
architectures=esp32
includes=M5UnitUnified.h
depends=M5Utility,M5HAL
